<?php
// $Id$

/**
 * Implementation of hook_perm().
 */
function vud_comment_perm() {
  return array('administer vote up/down on comments', 'use vote up/down on comments');
}

/**
 * Implementation of hook_menu().
 */
function vud_comment_menu() {
  $items = array();
  $items['admin/settings/voteupdown/comment'] = array(
    'title'            => 'Comments',
    'description'      => 'Vote Up/Down Comment settings',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('vud_comment_admin_settings'),
    'access arguments' => array('administer vote up/down on comments'),
    'type'             => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Menu callback for administration settings.
 */
function vud_comment_admin_settings() {
  $form['vud_comment_which_nodes'] = array(
    '#type'        => 'fieldset',
    '#title'       => t('Node types'),
    '#description' => t('Select the node types for which voting on comments will be activated.'),
  );
  $form['vud_comment_which_nodes']['vud_comment_node_types'] = array(
    '#type'          => 'checkboxes',
    '#title'         => t('Types'),
    '#default_value' => variable_get('vud_comment_node_types', array()),
    '#options'       => node_get_types('names'),
  );
  $form['vud_comment_widget_select'] = array(
    '#type'        => 'fieldset',
    '#title'       => t('Widget Selection'),
    '#description' => t('Select the voting widget that will be displayed.'),
  );
  $form['vud_comment_widget_select']['vud_comment_widget'] = array(
    '#type'          => 'radios',
    '#title'         => 'Widget selection',
    '#default_value' => variable_get('vud_comment_widget', 0),
    '#options'       => vud_read_widgets(),
  );
  return system_settings_form($form);
}

/**
 * Implementation of hook_comment().
 */
function vud_comment_comment(&$comment, $op) {
  switch ($op) {
    case 'view':
      if (user_access('use vote up/down on comments')) {
        $widget = variable_get('vud_comment_widget', 0);
        $comment->comment = theme("vud_widget", $comment->cid, 'comment', $widget) . $comment->comment;
      }
      break;
  }
}

/**
 * Implementation of hook_theme().
 */
function vud_comment_theme() {
  $widget_theme = variable_get('vud_comment_widget', 0);
  $widgetpath   = drupal_get_path('module', 'vud');
  return array(
    'vud_widget' => array(
      'arguments' => array('cid'  => NULL, 'type' => NULL, 'widget_theme' => NULL, 'tag' => NULL),
      'template'  => "widgets/$widget_theme/widget",
      'path'      => "$widgetpath",
    ),
    'vud_votes' => array(
      'arguments' => array('cid'  => NULL, 'type' => NULL, 'tag'  => NULL),
      'template'  => "widgets/$widget_theme/votes",
      'path'      => "$widgetpath",
    ),
  );
}

