<?php
// $Id$

/**
 * @file
 * Adds a voting widget to terms.
 */

/**
 * Implementation of hook_perm().
 */
function vud_term_perm() {
  return array('use vote up/down on terms', 'administer vote up/down on terms');
}

/**
 * Implementation of hook_menu().
 */
function vud_term_menu() {
  $items = array();
  $items['admin/settings/voteupdown/term'] = array(
    'title'            => 'Terms',
    'description'      => 'Vote Up/Down Term settings',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('vud_term_admin_settings'),
    'access arguments' => array('administer vote up/down on terms'),
    'type'             => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Advanced menu settings callback.
 */
function vud_term_admin_settings() {
  $form['vud_term_which_nodes'] = array(
    '#type'          => 'fieldset',
    '#title'         => t('Node types'),
    '#description'   => t('Select the node types you want to activate voting on:'),
  );
  $form['vud_term_which_nodes']['vud_term_types'] = array(
    '#type'          => 'checkboxes',
    '#default_value' => variable_get('vud_term_types', array()),
    '#options'       => node_get_types('names'),
  );
  $form['vud_term_widget_select'] = array(
    '#type'          => 'fieldset',
    '#title'         => t('Widget Selection'),
    '#description'   => t('Select the voting widget that will be displayed:'),
  );
  $form['vud_term_widget_select']['vud_term_widget'] = array(
    '#type'          => 'radios',
    '#default_value' => variable_get('vud_term_widget', 0),
    '#options'       => vud_read_widgets(),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_nodeapi().
 */
function vud_term_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'view':
      if (user_access('use vote up/down on terms')) {
        $node_type = in_array($node->type, variable_get('vud_term_types', array()), TRUE);
        if ($node_type) {
          $widget = variable_get('vud_term_widget', 0);
          $header = array(
            array('data' => t('Term')),
            array('data' => t('Description')),
            array('data' => t('Vote')),
            array('data' => t('Score')),
          );
          $rows[] = array("hello", "world", "this is", "pratul");
          $node->content['vud_term_show_table'] = array(
            '#value' => theme('table', $header, $rows),
            '#weight' => 0,
          );
        }
      }
  }
}
