<?php
// $Id$

/**
 * @file
 * Adds a voting widget to nodes.
 */

/**
 * Implementation of hook_perm().
 */
function vud_node_perm() {
  return array('use vote up/down on nodes', 'administer vote up/down on nodes', 'see vote up/down node stats');
}

/**
 * Implementation of hook_menu().
 */
function vud_node_menu() {
  $items = array();

  $items['admin/settings/voteupdown/node'] = array(
    'title'            => 'Nodes',
    'description'      => 'Vote Up/Down Node settings',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('vud_node_admin_settings'),
    'access arguments' => array('administer vote up/down on nodes'),
    'weight'           => -10,
    'type'             => MENU_LOCAL_TASK,
  );

  $items['node/%node/votes'] = array(
    'title'            => 'Voting details',
    'page callback'    => 'vud_node_tracker',
    'access arguments' => array('see vote up/down node stats'),
    'type'             => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Advanced menu settings callback.
 */
function vud_node_admin_settings() {
  $form['vud_node_which_nodes'] = array(
    '#type'          => 'fieldset',
    '#title'         => t('Node types'),
    '#description'   => t('Select the node types you want to activate voting on:'),
  );
  $form['vud_node_which_nodes']['vud_node_types'] = array(
    '#type'          => 'checkboxes',
    '#default_value' => variable_get('vud_node_types', array()),
    '#options'       => node_get_types('names'),
  );
  $form['vud_node_widget_select'] = array(
    '#type'          => 'fieldset',
    '#title'         => t('Widget Selection'),
    '#description'   => t('Select the voting widget that will be displayed:'),
  );
  $form['vud_node_widget_select']['vud_node_widget'] = array(
    '#type'          => 'radios',
    '#default_value' => variable_get('vud_node_widget', 'plain'),
    '#options'       => vud_read_widgets(),
  );
  $form['vud_node_votes_display'] = array(
    '#type'          => 'fieldset',
    '#title'         => t('Votes display'),
    '#description'   => t('Choose if the total number of votes will be displayed in the links part:'),
  );
  $form['vud_node_votes_display']['vud_node_votes'] = array(
    '#type'          => 'radios',
    '#default_value' => variable_get('vud_node_votes', 0),
    '#options'       => array(0 => 'No', 1 => 'Teaser only', 2 => 'Full display only', 3 => 'Both teaser and full'),
  );
  $form['vud_node_reset_votes'] = array(
    '#type'          => 'fieldset',
    '#title'         => t('Allow votes reset'),
    '#description'   => t('Choose if users are allowed to reset their vote on a node:'),
  );
  $form['vud_node_reset_votes']['vud_node_reset'] = array(
    '#type'          => 'radios',
    '#default_value' => variable_get('vud_node_reset', 0),
    '#options'       => array(0 => 'No', 1 => 'Yes'),
  );

return system_settings_form($form);
}

/**
 * Implementation of hook_nodeapi().
 */
function vud_node_nodeapi(&$node, $op, $teaser = NULL, $page = NULL) {
  switch ($op) {
    case 'view':
      if (user_access('use vote up/down on nodes')) {
        $node_type = in_array($node->type, variable_get('vud_node_types', array()), TRUE);
        $tag = variable_get('vud_tag', 'vote');
        if ($node_type) {
          $widget = variable_get('vud_node_widget', 'plain');
          $node->content['vud_node_widget_display'] = array(
            '#value' => theme('vud_widget', $node->nid, 'node', $tag, $widget),
            '#weight' => -10,
          );
        }
      }
  }
}

/**
 * Implementation of hook_theme().
 */
function vud_node_theme() {
  return array(
    'vud_widget' => array(
      'arguments' => array('cid' => NULL, 'type' => NULL, 'tag' => NULL, 'widget_theme' => NULL),
      'function'  => 'vud_widget_proxy',
    ),
    'vud_votes' => array(
      'arguments' => array('cid' => NULL, 'type' => NULL, 'tag' => NULL, 'widget_theme' => NULL),
      'function'  => 'vud_votes_proxy',
    ),
  );
}

/**
 * Menu callback; display all votes for a node.
 */
function vud_node_tracker() {
  if ($node = menu_get_object()) {
    $header = array(
      array('data' => t('User')),
      array('data' => t('Vote')),
      array('data' => t('Date'))
    );
    $tag = variable_get('vud_tag', 'vote');
    $criteria = array('content_type' => 'node', 'content_id' => $node->nid, 'tag' => $tag);
    $votes = votingapi_select_votes($criteria);
    foreach ($votes as $vote) {
      $account = user_load(array('uid' => $vote['uid'], 'status' => 1));
      $rows[] = array(
        theme('username', $account),
        $vote['value'],
        array('data' => format_date($vote['timestamp'], 'small'), 'class' => 'nowrap')
      );
    }
    drupal_set_title(check_plain($node->title));
    $output = theme('table', $header, $rows);
    $output .= theme('pager', NULL, 30);

    return $output;
  }
  else {
    drupal_not_found();
  }
}

/**
 * Implementation of hook_link().
 */
function vud_node_link($type, $object, $teaser = FALSE) {
  $links = array();
  switch ($type) {
    case 'node':
      $node = &$object;
      $votes_display_mode = variable_get('vud_node_votes', 0);
      $node_type = in_array($node->type, variable_get('vud_node_types', array()), TRUE);
      $widget_theme = variable_get('vud_node_widget', 'plain');
      $tag = variable_get('vud_tag', 'vote');
      switch ($votes_display_mode) {
        case 0:
          break;
        case 1:
          if (($teaser == 1) && $node_type && user_access('use vote up/down on nodes')) {
            $links['vud_node_votes_count'] = array(
              'title' => theme('vud_votes', $node->nid, $type, $tag, $widget_theme),
              'html'  => TRUE,
            );
          }
          break;
        case 2:
          if (($teaser == 0) && $node_type && user_access('use vote up/down on nodes')) {
            $links['vud_node_votes_count'] = array(
              'title' => theme('vud_votes', $node->nid, $type, $tag, $widget_theme),
              'html'  => TRUE,
            );
          }
          break;
        case 3:
          if ($node_type && user_access('use vote up/down on nodes')) {
            $links['vud_node_votes_count'] = array(
              'title' => theme('vud_votes', $node->nid, $type, $tag, $widget_theme),
              'html'  => TRUE,
            );
          }
          break;
      }
      if (variable_get('vud_node_reset', 0)) {
        $reset_token = drupal_get_token("votereset/node/$node->nid/$tag");
        $links['vud_node_votes_reset_link'] = array(
          'title' => t('Reset your vote'),
          'href'  => "votereset/node/$node->nid/$tag/$reset_token",
          'html'  => TRUE,
        );
      }
      break;
  }
  return $links;
}
